image: node:latest

before_script:
  - export NODE_ENV=test

variables:
  DB_HOST: mongo
  DB_PORT: 27017


stages:
  - install
  - test
  - production

cache:
  paths:
    - node_modules/

services:
  - mongo
  
install:
  stage: install
  script:
    - npm install
  artifacts:
    paths:
      - node_modules/
  
test:
  stage: test
  script: 
    - npm test

production:
  type: deploy
  stage: production
  image: ruby:latest
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=nodejs-project-template --api-key=$HEROKU_API_KEY --skip_cleanup
  only:
    - master

    